### ISSUE TITLE
Userscripts end in .user.js

### ISSUE THREAD

**Issue by Martii** [Desnoo/Proxer.me-HD-Video-Controls#1]
Please rename your script here on GitHub before you publish to OUJS... so it is a [Userscript](https://openuserjs.org/about/Userscript-Beginners-HOWTO#what-is-a-user-script-) and not a library.

Thanks
Admin OUJS

**Comment by Desnoo** [comment]
Sorry, fixed it right away.

Best regards,
Desnoo
